### ISSUE TITLE
Uncaught TypeError: interval.unref is not a function

### ISSUE THREAD

**Issue by Adrodoc** [atom-haskell-archive/haskell-ghc-mod#242]
[Enter steps to reproduce:]

1. Install Atom (https://atom.io/)
2. Install Stack (https://docs.haskellstack.org/en/stable/README/#how-to-install)
3. In some folder run:
    1. `stack new scribble`
    2. `cd scribble`
    3. `stack install ghc-mod hoogle hasktags pointfree pointful cabal-install`
    4. `stack install brittany`
    5. `stack --resolver lts-9 install ghc-mod`
    6. `stack config set resolver lts-9`
4. Open the folder `scribble`
5. Install package `atom-haskell` (via File > Settings > Install)
6. In the pop up click `Use default settings`
7. Open the file `scribble/app/Main.hs`
8. The `TypeError` should pop up in Atom

**Atom**: 1.46.0 x64
**Electron**: 4.2.7
**OS**: Windows 10
**Thrown From**: [haskell-ghc-mod](https://github.com/atom-haskell/haskell-ghc-mod) package 2.2.5

### Stack Trace

Uncaught TypeError: interval.unref is not a function

```
At C:\Users\User\.atom\packages\haskell-ghc-mod\node_modules\pidusage\lib\history.js:42

TypeError: interval.unref is not a function
    at sheduleInvalidator (/packages/haskell-ghc-mod/node_modules/pidusage/lib/history.js:42:16)
    at Object.set (/packages/haskell-ghc-mod/node_modules/pidusage/lib/history.js:29:5)
    at /packages/haskell-ghc-mod/node_modules/pidusage/lib/wmic.js:107:15
    at /packages/haskell-ghc-mod/node_modules/pidusage/lib/bin.js:44:5)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-haskell 0.4.0 
autocomplete-haskell 1.0.1 
busy-signal 2.0.1 
document-outline 2.1.2 
haskell-ghc-mod 2.2.5 
haskell-pointfree 0.2.0 
haskell-scry 1.0.9 
hasklig 0.4.0 
ide-haskell 2.4.1 
ide-haskell-cabal 2.5.0 
ide-haskell-hasktags 0.0.17 
ide-haskell-hoogle 0.1.2 
ide-haskell-repl 0.10.0 
intentions 1.1.5 
language-haskell 1.19.4 
language-haskell-scoped 0.1.1 
language-lua 0.9.11 
linter 2.3.1 
linter-ui-default 1.8.1 
markdown-pdf 2.3.3 
markdown-preview-plus 3.11.5 
mcfunction 0.6.4 
Sublime-Style-Column-Selection 1.7.5 
```

**Comment by lierdakil** [comment]
Thank you for reporting!

This was introduced in pidusage-2.0.19 apparently. I've released haskell-ghc-mod@v2.2.6 with stricter limits on pidusage version range, which should hopefully work for the time being.

Also reported upstream https://github.com/soyuka/pidusage/issues/109
